---
title: "final_project"
author: "Daniel Shapiro"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(infer)
library(gt)
library(gganimate)
library(janitor)
library(reshape2)
library(sf)
library(maps)
```

```{r btrends}
load("~/class-2019-09-10/final_project/rus_data/ICPSR_35355/DS0010/35355-0010-Data.rda")

sq <- str_squish(da35355.0010$NAME)

# I took out the white space in the string here. I figured it would be easier and cleaner that way.

trends <- cbind(sq, da35355.0010)

# I bound together the squished string and the original data set, and then selected the squished name column below.

gendat <- trends[-c(841:861), ] %>%
  select(sq, ID, YEAR, BIRTH, MORT, ARR_INT, DEP_INT)

# I took out lines 841-861, which are Magadan Oblast. For whatever reason, the other dataset has no data for Magadan Oblast. I also cut down on the variables to clean up the data.

gendat2 <- gendat %>%
  filter(YEAR == "2010") %>%
  mutate_all(~replace(., is.na(.), 0))

# I decided to make the year equal 2010 to give the most recent overview of data. I also changed my NAs to zeros so that I could get my merge to run.

outline <- read_rds("gadm36_RUS_1_sf.rds") %>%
  select(GID_1, NAME_1, VARNAME_1) %>%
  filter(NAME_1 != "Maga Buryatdan") %>%

# There was a lot of excess data in here. I didn't need it. I also filtered out "Maga Buryatdan" because it was elided into a different province in the actual data. Below, I had to recode all of the names so that I could match the two sets together. I thought long and hard about how to do this more efficiently, but this does the trick for this data set. Obviously, for longer data sets, it just would have been infeasible. But for one with such a small number of values, I figured it would work. I sincerely apologize for all of the code.


mutate(sq = (recode(NAME_1, "Adygey" = "Republic of Adygea",
       "Altay" = "Altai Krai",
       "Amur" = "Amur Oblast",
       "Arkhangel'sk" = "Arkhangelsk Oblast",
       "Astrakhan'" = "Astrakhan Oblast",
       "Bashkortostan" = "Republic of Bashkortostan",
       "Belgorod" = "Belgorod Oblast",
       "Bryansk" = "Bryansk Oblast",
       "Buryat" = "Republic of Buryatia",
       "Chechnya" = "Chechen Republic",
       "Chelyabinsk" = "Chelyabinsk Oblast",
       "Chukot" = "Chukotka Autonomous Okrug",
       "Chuvash" = "Chuvash Republic",
       "City of St. Petersburg" = "Saint Petersburg",
       "Dagestan" = "Republic of Dagestan",
       "Gorno-Altay" = "Altai Republic",
       "Ingush" = "Republic of Ingushetia",
       "Irkutsk" = "Irkutsk Oblast",
       "Ivanovo" = "Ivanovo Oblast",
       "Kabardin-Balkar" = "Kabardino-Balkar Republic",
       "Kaliningrad" = "Kaliningrad Oblast",
       "Kalmyk" = "Republic of Kalmykia",
       "Kaluga" = "Kaluga Oblast",
       "Kamchatka" = "Kamchatka Krai",
       "Karachay-Cherkess" = "Karachay-Cherkess Republic",
       "Karelia" = "Republic of Karelia",
       "Kemerovo" = "Kemerovo Oblast",
       "Khabarovsk" = "Khabarovsk Krai",
       "Khakass" = "Republic of Khakassia",
       "Khanty-Mansiy" = "Khanty-Mansi Autonomous Okrug-Yugra",
       "Kirov" = "Kirov Oblast",
       "Komi" = "Komi Republic",
       "Kostroma" = "Kostroma Oblast",
       "Krasnodar" = "Krasnodar Krai",
       "Krasnoyarsk" = "Krasnoyarsk Krai",
       "Kurgan" = "Kurgan Oblast",
       "Kursk" = "Kursk Oblast",
       "Leningrad" = "Leningrad Oblast",
       "Lipetsk" = "Lipetsk Oblast",
       "Mariy-El" = "Mari El Republic",
       "Mordovia" = "Republic of Mordovia",
       "Moscow City" = "Moscow",
       "Moskva" = "Moscow Oblast",
       "Murmansk" = "Murmansk Oblast",
       "Nizhegorod" = "Nizhny Novgorod Oblast",
       "North Ossetia" = "Republic of North Ossetia-Alania",
       "Novgorod" = "Novgorod Oblast",
       "Novosibirsk" = "Novosibirsk Oblast",
       "Omsk" = "Omsk Oblast",
       "Orel" = "Oryol Oblast",
       "Orenburg" = "Orenburg Oblast",
       "Penza" = "Penza Oblast",
       "Perm'" = "Perm Krai",
       "Primor'ye" = "Primorsky Krai",
       "Pskov" = "Pskov Oblast",
       "Rostov" = "Rostov Oblast",
       "Ryazan'" = "Ryazan Oblast",
       "Sakha" = "Sakha (Yakutia) Republic",
       "Sakhalin" = "Sakhalin Oblast",
       "Samara" = "Samara Oblast",
       "Saratov" = "Saratov Oblast",
       "Smolensk" = "Smolensk Oblast",
       "Stavropol'" = "Stavropol Krai",
       "Sverdlovsk" = "Sverdlovsk Oblast",
       "Tambov" = "Tambov Oblast",
       "Tatarstan" = "Republic of Tatarstan",
       "Tomsk" = "Tomsk Oblast",
       "Tula" = "Tula Oblast",
       "Tuva" = "Tuva Republic",
       "Tver'" = "Tver Oblast",
       "Tyumen'" = "Tyumen Oblast",
       "Udmurt" = "Udmurt Republic",
       "Ul'yanovsk" = "Ulyanovsk Oblast",
       "Vladimir" = "Vladimir Oblast",
       "Volgograd" = "Volgograd Oblast",
       "Vologda" = "Vologda Oblast",
       "Voronezh" = "Voronezh Oblast",
       "Yamal-Nenets" = "Yamalo-Nenets Autonomous Okrug",
       "Nenets" = "Yamalo-Nenets Autonomous Okrug",
       
# I just made "Nenets" equal the broader Yamal-Nenets Autonomous Okrug. Some people split them and some don't; it's just easier to do it this way for purposes of this day.
       
       "Yaroslavl'" = "Yaroslavl Oblast",
       "Yevrey" = "Jewish Autonomous Oblast",
       "Zabaykal'ye" = "Zabaykalsky Krai"))) %>%
  mutate(sq = as.factor(sq))

Shape <- merge(gendat2, outline, by = 'sq') %>%
  drop_na()
```

```{r birth summary}

birs <- ggplot(data = Shape, aes(geometry = geometry, fill = BIRTH)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma", trans = "sqrt") +

# I wanted a color scheme that could be seen well, so I put the scheme to plasma, and made the colors coordinate to the square root instead of the pure data. This makes differences more visible.

  coord_sf(xlim = c(20, 179), expand = FALSE) +
  labs(title = "Birthrate by Region, 2010*",
       caption = "*Not including Magadan Oblast",
       x = "Longitude",
       y = "Latitude",
       fill = "Birth Rate (%)")

write_rds(birs, path = "popshiny/bir2010.rds")

# Wrote rds to my shiny app folder.
```

```{r mort summary}
# I'm making the exact same map for mortality rates in 2010 -- the code is essentially identical to the previous chunk.

mors <- ggplot(data = Shape, aes(geometry = geometry, fill = MORT)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma", trans = "sqrt") +
  coord_sf(xlim = c(20, 179), expand = FALSE) +
  labs(title = "Mortality Rate by Region, 2010*",
       caption = "*Not including Magadan Oblast",
       x = "Longitude",
       y = "Latitude",
       fill = "Mortality Rate (%)")

write_rds(mors, path = "popshiny/mor2010.rds")

# Wrote rds.
```

```{r birth}
birthdata <- da35355.0010 %>%
  clean_names() %>%
    filter(year != "1990",
         year != "1991") %>%
  select(id, year, name, birth, mort)

# I first filtered out 1990 and 1991, because in both of those years, Russia was still part of the Soviet Union for at least part of the time.

write_rds(birthdata, path = "popshiny/birthdata.rds")
```

```{r mort}
mortdata <- da35355.0010 %>%
  clean_names() %>%
  filter(year != "1990",
         year != "1991") %>%
  select(id, year, name, birth, mort)

# I suppose that creating this isn't entirely necessary, seeing as how the birth rds would have done the trick as well. Still, I feel like it will get less confusing in the shiny code.

write_rds(mortdata, path = "popshiny/mortdata.rds")
```

```{r migr}
migrdata <- da35355.0010 %>%
  clean_names() %>%
  filter(year != "1990",
         year != "1991",
         year != "1992",
         year != "1993",
         year != "1994",
         year != "1995",
         year != "1996") %>%

# Here I had to cut a number of years; unfortunately, there was a lot of missing data over the period from 1992-1996. I was already planning on cutting 1990 and 1991 as it was.
  
  select(year, name, arr_int, dep_int) %>%
  melt(id = c("year", "name"))

# I had to melt the data to get the arrival and departure data into one column. I'll be able to create a geom_col graph in this way that has two columns for each year -- an arrival and a departure.

write_rds(migrdata, path = "popshiny/migrdata.rds")
```

